### ISSUE TITLE
When to release a new version

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/ngshare#122]
I'm not entirely sure if I should release a new version after PR #120. Releasing versions too frequently is kinda bad since users will have to keep updating, but also that feature is useful for at least a couple of people so we should probably make it available sooner rather than later. @lxylxy123456 What do you think?

**Comment by lxylxy123456** [comment]
I think we can regularly (e.g. every 2 weeks or 1 month) push a new version as long as there are changes, so that people can get the features in a bounded time and do not need to update too frequently (since we can combine commits). 

This should be something we need to learn and figure out. 

Also, I think for users updating to the latest version is not mandatory, so they can ignore a possible update.

**Comment by rkevin-arch** [comment]
I asked Jason, and he thinks releasing versions ASAP as soon as PRs come in is a good idea. The user can always choose to not upgrade if it doesn't concern them, and we do have a fairly automated way to release new versions (merge to stable).

**Comment by lxylxy123456** [comment]
Sounds good. I think you can how close this issue.
