### ISSUE TITLE
Cannot launch pod in GKE: ReadWriteMany not supported

### ISSUE THREAD

**Issue by wmwolf** [LibreTexts/ngshare#138]
I'm working my way towards installing ngshare alongside z2jh in a GKE environment. As I went through the instructions (thanks for the excellent documentation!), I am unable to get the ngshare pod running, and it seems to have to do with the fact that the persistent volume cannot be provisioned. The pod never starts up, and when I check on the storage in the google cloud console, I get the the following for the ngshare-pvc:

`Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported`

To get here, I followed the instructions up to and including [Configuring Z2JH to Work with ngshare](https://ngshare.readthedocs.io/en/latest/user_guide/install_z2jh.html#configuring-z2jh-to-work-with-ngshare), and I do see ngshare in the services menu in my JupyterHub account, but clicking on it understandably gives me a 503. I have not yet patched my DockerFile, since it doesn't seem I can even get ngshare to function at all.

In my little research thus far, it looks like GCE doesn't allow ReadWriteMany for PVCs. Is this something that can be handled in the configuration of ngshare, or do I need to go on a GKE spirit journey to learn more about persistent storage with google cloud?

**Comment by rkevin-arch** [comment]
You don't need `ReadWriteMany`. Add the following to the helm values:
```yaml
pvc:
  accessModes:
    - ReadWriteOnce
```
It was `ReadWriteMany` by default half due to a bug and half due to us
wanting to make ngshare highly available (but we dropped that eventually).
There should be no problems creating the PVC as `ReadWriteOnce`.

BTW, you can see a list of all the helm values you can specify (and their
defaults) [here](
https://github.com/LibreTexts/ngshare/blob/master/helmchart/ngshare/values.yaml
).

**Comment by rkevin-arch** [comment]
You don't need `ReadWriteMany`. Add the following to the helm values:
```yaml
pvc:
  accessModes:
    - ReadWriteOnce
```
It was `ReadWriteMany` by default [half due to a bug](https://github.com/LibreTexts/ngshare/issues/133#issuecomment-685193751) and half due to us wanting to make ngshare highly available (but we dropped that eventually). There should be no problems creating the PVC as `ReadWriteOnce`.

BTW, you can see a list of all the helm values you can specify (and their defaults) [here](
https://github.com/LibreTexts/ngshare/blob/master/helmchart/ngshare/values.yaml
).

(Reposted due to email replies not supporting markdown)

**Comment by wmwolf** [comment]
Awesome, and thanks for the clarification. I saw that I could configure `pvc.accessModes`, but my mind was still stuck thinking of ngshare as a shared database, so it didn't even occur to me to change it up. Now I just need to get the default `nbgrader_config.py` files updated by my dockerfile and I'll be good to go!
